### ISSUE TITLE
Feature: Customize message in "support-reuests" channel

### ISSUE THREAD

**Issue by ChristopherSchek** [NovaFox161/TicketBird-Discord-Bot#17] opened 2022-02-09 18:40 UTC
Would be great to have the ability to update/edit the message that TicketBird posts at the top of the "support-request" channel so we can provide users with better instructions/stylize it.

**Comment by smnc** [comment] 2022-08-31 02:12
Duplicate of issue #13

**Closed as completed by smnc** 2022-08-31 02:12 UTC
Labels: duplicate
